:caution-caption: :Draft work:

= Working with GitHub : DGIWG how to

== Introduction to GitHub
GitHub is a code hosting platform for version control and collaboration. It lets you and others work together on projects.

== Required tools
This chapter is inspirited from some OGC guidelines to develop OGC reports (https://portal.opengeospatial.org/files/?artifact_id=73351)

A *web browser* is required to access https://github.com/ web site (account creation, forking repository ...)

_Online editing_

Online editing of asciidoc document is possible, directly with a web browser. This solution does not offer advance functionalities (visual preview, spellcheck...) that are available offline with dedicated tools.

_Offline editing_

*GitHub desktop software* is recommended to manage GitHub resources. It provides a graphic interface to clone, merge, pull...resources).

[NOTE]
Git command lines may also be used (without any graphic interface) to manage resources.

A *text editor* is required to edit text locally (offline);  Atom software is recommended, but other text editors may be used. Asciidoctor in combination of Atom is recommended for HTML and PDF generation.
Followings Atom packages are useful:

- asciidoc-preview
- autocomplete-asciidoc
- language-asciidoc
- markdown-writer: requires changing of key-map to allow for keyboard shortcuts such as e.g. bold
- platformio-IDE-terminal

This environment allows you to use keyboard shortcuts, autocomplete, syntax highlighting and a rendered preview for asciidoc; and provides you an terminal window within the editor to convert your asciidoc to html and pdf

Although GitHub can be used anonymously, a GitHub user account is required to interact with the platform and to be able to fork repositories. GitHub is free for public repositories.

== Working on an existing repository
This first use case is useful when you want to collaborate to an existing project. That is the case for the DGIWG activity. In this case, the workflow is

* Go to the DGIWG project/repository you want to work on (for example https://github.com/DGIWG/sandbox)
* Fork the project to your account, so you have your own version.

* Clone on your machine your version of the repository (your fork that looks like https://github.com/yourNames/sandbox). This may be done with https://desktop.GitHub.com/[GitHub desktop tool].

=> this will create a copy of your repository on you local hard drive.

* Edit file locally (for example with Atom editor tool, check "Recommended AsciiDoc Environment" on https://portal.opengeospatial.org/files/?artifact_id=73351 for installing the tool and related plugins)
* Save file locally (still with the text editor)
* Commit locally (for example with GitHub desktop)
* Push to Fork (for example with GitHub desktop)

=> this will push your local changes to your own fork of the repository (https://github.com/yourName/sandbox)


== Pulling changes from your fork
* create a new pull request (from your own fork on GitHub.com, for example https://github.com/yourName/sandbox)

=> this pull request has then to be discussed and accepted by admin of the DGIWG repo (https://github.com/DGIWG/sandbox)

* once your pull request has been accepted by the DGIWG repo, you just need to synchronize your fork again with it by (with GitHub desktop for example)
  - comparing your local copy to the DGIWG branch https://github.com/DGIWG/sandbox)
  - make a merge (this will update your local clone of your own repository), then your local Copy = the DGIWG online repo (https://github.com/DGIWG/sandbox)
  - push it to the origin (this will update your online copy https://github.com/yourName/sandbox), then https://github.com/yourName/sandbox = https://github.com/DGIWG/sandbox


== Working on a new project
How to create a new project?
The easiest is to use the GitHub UI to create a new project and then clone it.
You can also use the command line (more info https://help.github.com/en/github/importing-your-projects-to-github/adding-an-existing-project-to-github-using-the-command-line[here]).

== GitHub Flow
http://1.bp.blogspot.com/-n8gwrM5Bf04/UfosDLuuDUI/AAAAAAAAKwg/2aE3V0NDk-g/s1600/git-and-GitHub-workflow.png[GitHub Flow]
